name: Run Postman Tests

on:
  push:
    branches:
      - postman-tests-main # Ajuste para a branch que deseja monitorar
  pull_request:
    branches:
      - postman-tests-main # Ajuste para a branch que deseja monitorar

jobs:
  postman_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.18.0" # Use a versão Node.js compatível

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run collections\Server_Rest_API_(Happy Path).postman_collection.json -e environments\Server-Rest-Env.postman_environment.json
        env:
          API_KEY: ${{ secrets.API_KEY }} # Variáveis de ambiente, se precisar
