name: Run Postman Tests

on:
  push:
    branches:
      - postman-tests-main
  pull_request:
    branches:
      - postman-tests-main

jobs:
  postman_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.18.0"

      - name: Install Newman
        run: npm install -g newman

      - name: Run all Postman collections with all environments
        run: |
          for collection in collections/*.json; do
            for environment in environments/*.json; do
              echo "Running collection $collection with environment $environment"
              newman run "$collection" -e "$environment"
            done
          done
